version: "3.1"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lidlfanboys
      POSTGRES_DB: bearnaisee

  frontend:
    build: ./frontend
    depends_on:
      - api

  api:
    build: ./backend

volumes:
  postgres: null


