version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"

volumes:
  postgres: null
